FROM node:26-trixie

RUN apt-get update && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN npm ci

RUN npm run build -w=packages/backend

EXPOSE 3000

CMD ["npm", "run", "start", "-w=packages/backend"]