[variables]
NIXPACKS_PATH = "/usr/local/bin:/usr/bin:/bin"

[phases.setup]
nixPkgs = ["ffmpeg", "curl"]

cmd = [
    "curl -fsSL https://deb.nodesource.com/setup_26.x | bash -",
    "apt-get install -y nodejs"
]