import 'dart:convert';
import 'dart:io';

void main() {
  var rootDir = Directory.current.path;
  if (rootDir.endsWith('packages${Platform.pathSeparator}app')) {
    rootDir = Directory.current.parent.parent.path;
  }
  
  final jsonPath = '$rootDir/packages/shared/licenses/extra-packages.json';
  final outputPath = '$rootDir/packages/app/lib/generated_extra_licenses.dart';

  final jsonFile = File(jsonPath);
  if (!jsonFile.existsSync()) {
    print('Error: extra-packages.json not found at $jsonPath');
    exit(1);
  }

  final jsonContent = jsonFile.readAsStringSync();
  final List<dynamic> packages = jsonDecode(jsonContent);

  final buffer = StringBuffer();
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// This file is generated by packages/packaging/common/gen_extra_licenses.dart');
  buffer.writeln('');
  buffer.writeln('import \'oss_licenses.dart\';');
  buffer.writeln('');
  buffer.writeln('const generatedExtraPackages = <Package>[');

  for (final pkg in packages) {
    final name = pkg['name'];
    final description = pkg['description'] ?? '';
    final version = pkg['version'] ?? '';
    final homepage = pkg['homepage'] ?? '';
    final licenseFile = pkg['licenseFile'];
    
    String authors = '[]';
    if (pkg['authors'] != null) {
      final authorsList = List<String>.from(pkg['authors']);
      authors = '[${authorsList.map((a) => "'${a.replaceAll("'", "\\'")}'").join(', ')}]';
    }

    String spdx = '[]';
    if (pkg['spdxIdentifier'] != null) {
      spdx = '[\'${pkg["spdxIdentifier"]}\']';
    }

    String licenseText = 'License text not found';
    if (licenseFile != null) {
      final txtFile = File('$rootDir/packages/shared/licenses/$licenseFile');
      if (txtFile.existsSync()) {
        licenseText = txtFile.readAsStringSync().replaceAll('\$', '\\\$').replaceAll('\'', '\\\'');
      }
    }

    buffer.writeln('  Package(');
    buffer.writeln('    name: \'$name\',');
    buffer.writeln('    description: \'$description\',');
    buffer.writeln('    authors: $authors,');
    buffer.writeln('    version: \'$version\',');
    
    buffer.writeln('    license: \'\'\'');
    buffer.writeln(licenseText.replaceAll('\'\'\'', '\'\'\\\'')); // Escaping triple quotes just in case
    buffer.writeln('\'\'\',');

    buffer.writeln('    isMarkdown: false,');
    buffer.writeln('    isSdk: false,');
    buffer.writeln('    dependencies: [],');
    buffer.writeln('    devDependencies: [],');
    buffer.writeln('    homepage: \'$homepage\',');
    buffer.writeln('    spdxIdentifiers: $spdx,');
    buffer.writeln('  ),');
  }

  buffer.writeln('];');

  final outFile = File(outputPath);
  outFile.writeAsStringSync(buffer.toString());
  print('Successfully generated the extra packages list for the Dart app at $outputPath');
}
