name: App Dev Testing Build

on:
  push:
    branches:
      - dev
    paths:
      - 'packages/app/**'
      - 'packages/packaging/**'

  workflow_dispatch:

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y librsvg2-bin cmake pkg-config build-essential libgtk-3-dev liblzma-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: 'stable'

      - name: Cache Native Dependencies (Linux)
        id: cache_linux_deps
        uses: actions/cache@v5
        with:
          key: linux-deps-${{ hashFiles('packages/app/vendor/sonic_audio/build_native_deps_linux.sh') }}
          path: packages/app/vendor/sonic_audio/dependencies/linux-x64

      - name: Build Native Dependencies
        if: steps.cache_linux_deps.outputs.cache-hit != 'true'
        run: ./packages/app/vendor/sonic_audio/build_native_deps_linux.sh

      - name: Build Linux targets
        run: |
          cd packages/app
          flutter pub get
          dart run dart_pubspec_licenses:generate
          dart run ../packaging/common/gen_extra_licenses.dart
          flutter build linux --release
          cd ../../

          ./packages/packaging/linux/tarball.sh
          ./packages/packaging/linux/appimage.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: linux-artifacts
          path: packages/packaging/dist/*

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          cache: 'gradle'
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: 'stable'

      - name: Decode Keystore and create Properties
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > packages/app/android/app/release-keystore.jks

          cat <<EOF > packages/app/android/key.properties
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEYSTORE_PASSWORD
          keyAlias=release
          storeFile=app/release-keystore.jks
          EOF
        env:
          KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Generate Licenses
        run: |
          cd packages/app
          flutter pub get
          dart run dart_pubspec_licenses:generate
          dart run ../packaging/common/gen_extra_licenses.dart

      - name: Cache Native Dependencies (Android)
        id: cache_android_deps
        uses: actions/cache@v5
        with:
          key: android-deps-${{ hashFiles('packages/app/vendor/sonic_audio/build_native_deps_android.sh') }}
          path: packages/app/vendor/sonic_audio/dependencies/android

      - name: Build Native Dependencies
        if: steps.cache_android_deps.outputs.cache-hit != 'true'
        run: |
          export NDK_HOME="$ANDROID_HOME/ndk"
          ./packages/app/vendor/sonic_audio/build_native_deps_android.sh

      - name: Build Android APKs
        run: ./packages/packaging/linux/android.sh

      - name: Security Cleanup
        if: always()
        run: |
          rm -f packages/app/android/app/release-keystore.jks
          rm -f packages/app/android/key.properties

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: android-artifacts
          path: packages/packaging/dist/*

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Windows Desktop Dependencies
        uses: ilammy/msvc-dev-cmd@v1

      - name: Verify build tools
        shell: pwsh
        run: |
          cmake --version
          where.exe cl

      - name: Install NSIS
        shell: pwsh
        run: |
          choco install nsis -y

          echo "C:\Program Files (x86)\NSIS" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Check NSIS install
        shell: pwsh
        run: |
          where.exe makensis
          makensis /VERSION

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: 'stable'

      - name: Cache Native Dependencies (Windows)
        id: cache_windows_deps
        uses: actions/cache@v5
        with:
          key: windows-deps-${{ hashFiles('packages/app/vendor/sonic_audio/build_ffmpeg_windows.ps1') }}
          path: packages/app/vendor/sonic_audio/dependencies/windows

      - name: Build Native Dependencies
        if: steps.cache_windows_deps.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          ./packages/app/vendor/sonic_audio/build_ffmpeg_windows.ps1

      - name: Build Windows targets
        shell: pwsh
        run: |
          cd packages/app
          flutter pub get
          flutter build windows --release
          cd ../packaging/windows

          ./pack_windows.ps1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: windows-artifacts
          path: packages/packaging/windows/dist/*